source :rubygems

gem "cucumber", "~>1.1.4"
gem "selenium-webdriver", "2.21.2"
gem "rspec", "~>2.6.0"
gem "selenium-client", "~> 1.2.18"
gem "capybara", "~> 1.1.2"
gem "yard", "~>0.8.1"
gem "yard-cucumber", "~> 2.1.7"
gem "redcarpet", "~> 2.1.1"
gem "viewcumber", "~>0.3.1"
