default:  -r features/support -r features/step_definitions features ENVIRONMENT=QA
production:  -r features/support -r features/step_definitions features ENVIRONMENT=PRODUCTION
checkout:  -r features/support -r features/step_definitions features ENVIRONMENT=CHKOUT