#Script Name        :  errormessages
#Description        :  This file have all the error messages of macys.com functionality   
#Author             :  NISUM Technologies              
#Reviewer           :              
#Creation Date      :        
#Pre-conditions     :  Base environment, access to the Software Request System.
#Post-conditions:   :  Regression of the Software Request System based on functionality.
#Data Files         :  None at this level.
#******************************************************************************************************
# Revision History
#******************************************************************************************************
#Date               :                
#Revised By         :        
#******************************************************************************************************
#*********************************************************************************************

#********************************#### Shipping Page Validations ####*************************#
shippingFirstNameValidationMessage: First Name is a required field and may only contain letters and hyphens. Your entry may not exceed 20 characters.
shippingLastNameValidationMessage: Last Name is a required field and may only contain letters and hyphens. Your entry may not exceed 20 characters.
shippingAddress1ValidationMessage: "Street Address is a required field and may only contain letters, numbers and #. Your entry may not exceed 35 characters, including spaces."
shippingCityValidationMessage: City is a required field and may only contain letters, numbers and apostrophes.Your entry must not exceed 25 characters, including spaces.
shippingStateValidationMessage: You did not select a State from the menu. Please select a State to complete this form.
shippingZipcodeValidationMessage: Your Zip Code must be 5 digits. Please try again.
shippingPhoneNumberValidationMessage: Your Phone Number must be entered in this format: 800-555-1212 and may not all be the same number. Do not use (parentheses) for the area code. Please try again.

#Payment page error messages 
billingCardTypeVSCardNumberValidationErrorMsg: Invalid Credit Card.